### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by leerzeichen7** [Bahramrj/Assignment#10]
Can you set up Github pages for your repository?
This makes the review of the mobile version of the website much easier.

**Comment by Bahramrj** [comment]
I already did it. I think you should change `Home.html` to `index.html` in order to website show up.(according to the GitHub pages [document](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site))

**Comment by leerzeichen7** [comment]
You're right. Thank you

**Comment by leerzeichen7** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/84912693/149778960-3c6cb38f-ba42-491f-bc0d-67ea0e199b9f.png">

**Comment by leerzeichen7** [comment]
As you can see Github Pages is not working.
Can you help fixing it?

**Comment by leerzeichen7** [comment]
The source branch should be develop and the folder should be root.
And can you please share the link where pages is published?
Thanks

**Comment by Bahramrj** [comment]
<img width="823" alt="2022-01-17_14-52-32" src="https://user-images.githubusercontent.com/94145705/149781221-a879ac9f-a60d-4425-bac4-554c18da9978.png">

This is the setting of pages for repo. we had the same issue as you and we moved the docs folder from `Assignment/assignment-2b/docs` to `Assignment/docs` and delete all content of assignment-2b folder.

**Comment by a1d4c7** [comment]
Thank you it works now
