### ISSUE TITLE
Access to git repo

### ISSUE THREAD

**Issue by leerzeichen7** [Bahramrj/Assignment#5]
Hello everyone, please add @a1d4c7 and @leerzeichen7 as contributors to your git repository.

**Comment by Bahramrj** [comment]
Hello 
I added you as contributors, please confirm.
Best regards

**Comment by leerzeichen7** [comment]
I have access to the repo now. Thank you.
And I already created a develop branch where we can work safely

**Comment by a1d4c7** [comment]
I dont have write access to the repository. Could you please invite me again?

**Comment by Bahramrj** [comment]
> I dont have write access to the repository. Could you please invite me again?

Hi, I added you as contributors so please confirm.
Thank for informing

**Comment by a1d4c7** [comment]
Thanks it works now
