### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by leerzeichen7** [Bahramrj/Assignment#6]
There is a problem with the embedding of the logo. When we embed the logo into the website it is for some reason not visible. As a test we embedded our logo in the same way and it did work.
Do we have to take anything into consideration when embedding your provided logo?

**Comment by Bahramrj** [comment]
Hello, did you try to resize it? ( in svg code ).

> There is a problem with the embedding of the logo. When we embed the logo into the website it is for some reason not visible. As a test we embedded our logo in the same way and it did work. Do we have to take anything into consideration when embedding your provided logo?

**Comment by Bahramrj** [comment]
use the [raw address](https://raw.githubusercontent.com/Bahramrj/Assignment/develop/assignment-2b/docs/assets/Logo.svg) of the logo for `src="......"`

**Comment by leerzeichen7** [comment]
Unfortunately it still doesn't work

**Comment by Bahramrj** [comment]
I updated the source code of `logo.svg` in the master branch.

**Comment by leerzeichen7** [comment]
The new file you provided is now working. Thanks a lot
